import type { IcpProfile, Lead, LeadEvidence } from "../domain/lead";

export const DEMO_CAMPAIGN_ID = "9f1ed8e8-7d3a-4f12-b8a2-807a5860f6cc";
export const DEMO_ICP_ID = "d3c31310-62c7-4ed7-b4df-e068ebd48760";

const observedAt = "2026-07-21T09:30:00.000Z";
const createdAt = "2026-07-22T08:15:00.000Z";
const updatedAt = "2026-07-23T06:20:00.000Z";

function evidence(
  id: string,
  kind: LeadEvidence["kind"],
  sourceTitle: string,
  excerpt: string,
  sourceUrl: string,
  confidence: number,
): LeadEvidence {
  return {
    id,
    kind,
    provider: "Parallel",
    sourceTitle,
    excerpt,
    sourceUrl,
    confidence,
    observedAt,
  };
}

const shared = {
  organizationId: "demo-organization",
  campaignId: DEMO_CAMPAIGN_ID,
  icpProfileId: DEMO_ICP_ID,
  icpName: "European B2B SaaS revenue teams",
  createdAt,
  updatedAt,
} as const;

export const demoLeads: Lead[] = [
  {
    ...shared,
    id: "f8b91144-2041-4a3b-80fc-98b6984bc73a",
    companyName: "Northstar Cloud",
    companyDomain: "northstarcloud.eu",
    companySize: "51–200",
    industry: "B2B SaaS",
    geography: "Amsterdam, NL",
    personName: "Elena Visser",
    jobTitle: "VP Revenue",
    email: "elena@northstarcloud.eu",
    emailVerified: true,
    phone: "+31 20 555 0184",
    phoneVerified: true,
    linkedinUrl: "https://www.linkedin.com/in/elena-visser",
    confidence: 94,
    confidenceBand: "high",
    status: "qualified",
    doNotContact: false,
    buyingSignals: ["Hiring two SDRs", "Recently expanded into Germany"],
    evidence: [
      evidence(
        "18021737-8ee3-4df9-a759-5cd4339c8881",
        "intent",
        "Northstar Cloud careers",
        "Open roles for two outbound SDRs and a Revenue Operations Manager.",
        "https://northstarcloud.eu/careers",
        96,
      ),
      evidence(
        "e189b04a-663f-4f50-857a-3c299706e5ef",
        "person",
        "Northstar Cloud leadership",
        "Elena Visser owns revenue strategy across Benelux and DACH.",
        "https://northstarcloud.eu/company",
        92,
      ),
    ],
  },
  {
    ...shared,
    id: "d7d98ab8-acde-4f88-9c0f-5df130d9b0bc",
    companyName: "Orbit Ledger",
    companyDomain: "orbitledger.com",
    companySize: "201–500",
    industry: "Fintech",
    geography: "London, UK",
    personName: "Marcus Reed",
    jobTitle: "Head of Growth",
    email: "marcus.reed@orbitledger.com",
    emailVerified: true,
    phone: null,
    phoneVerified: false,
    linkedinUrl: "https://www.linkedin.com/in/marcus-reed-growth",
    confidence: 89,
    confidenceBand: "high",
    status: "approved",
    doNotContact: false,
    buyingSignals: ["Launched mid-market plan", "New outbound growth mandate"],
    evidence: [
      evidence(
        "0db7eebc-a2af-41b6-a24b-97ae387e26e6",
        "company",
        "Orbit Ledger product update",
        "The company introduced a mid-market package for finance teams with 100–500 employees.",
        "https://orbitledger.com/updates/mid-market",
        91,
      ),
      evidence(
        "34ce168b-193d-48f7-aa62-3973d4b7a81c",
        "contact",
        "Orbit Ledger contact pattern",
        "The work email follows the company’s published first.last pattern and passed verification.",
        "https://orbitledger.com/contact",
        88,
      ),
    ],
  },
  {
    ...shared,
    id: "a2163899-033e-4e5e-ac4a-67c6dbc52f90",
    companyName: "Kiteframe",
    companyDomain: "kiteframe.io",
    companySize: "51–200",
    industry: "Developer tools",
    geography: "Berlin, DE",
    personName: "Sofia Klein",
    jobTitle: "Director of Demand Generation",
    email: "sofia@kiteframe.io",
    emailVerified: true,
    phone: "+49 30 5557 1209",
    phoneVerified: false,
    linkedinUrl: "https://www.linkedin.com/in/sofia-klein-demand",
    confidence: 84,
    confidenceBand: "high",
    status: "needs_review",
    doNotContact: false,
    buyingSignals: ["Series A announced", "First demand generation leader"],
    evidence: [
      evidence(
        "96edacdd-992b-47a9-bba5-ea31f1df6f90",
        "intent",
        "Kiteframe funding announcement",
        "Kiteframe will use its Series A to build a repeatable commercial motion in Europe.",
        "https://kiteframe.io/blog/series-a",
        90,
      ),
    ],
  },
  {
    ...shared,
    id: "930b1e21-e14b-471b-8496-1a6a8a8f90f6",
    companyName: "Cedar Metrics",
    companyDomain: "cedarmetrics.se",
    companySize: "11–50",
    industry: "Analytics",
    geography: "Stockholm, SE",
    personName: "Jonas Lind",
    jobTitle: "Co-founder & CEO",
    email: "jonas@cedarmetrics.se",
    emailVerified: true,
    phone: null,
    phoneVerified: false,
    linkedinUrl: "https://www.linkedin.com/in/jonas-lind",
    confidence: 76,
    confidenceBand: "medium",
    status: "qualified",
    doNotContact: false,
    buyingSignals: ["Founder-led sales", "Seeking repeatable outbound motion"],
    evidence: [
      evidence(
        "20992de9-b588-409d-b49e-d0c9ca173f45",
        "person",
        "Cedar Metrics founder interview",
        "Jonas describes moving from referrals toward a repeatable acquisition channel.",
        "https://cedarmetrics.se/journal/founder-interview",
        79,
      ),
    ],
  },
  {
    ...shared,
    id: "cdfda24f-0e88-4cc8-b87a-590ce942f256",
    companyName: "Fieldstone AI",
    companyDomain: "fieldstone.ai",
    companySize: "51–200",
    industry: "AI infrastructure",
    geography: "Paris, FR",
    personName: "Camille Moreau",
    jobTitle: "Revenue Operations Lead",
    email: "camille@fieldstone.ai",
    emailVerified: false,
    phone: "+33 1 87 65 42 18",
    phoneVerified: true,
    linkedinUrl: "https://www.linkedin.com/in/camille-moreau-revops",
    confidence: 72,
    confidenceBand: "medium",
    status: "new",
    doNotContact: false,
    buyingSignals: ["CRM migration underway", "RevOps team newly formed"],
    evidence: [
      evidence(
        "2eb41bfd-acde-40f7-9ba5-a26d46ce13c7",
        "company",
        "Fieldstone AI operations role",
        "A new role references rebuilding CRM workflows and outbound reporting.",
        "https://fieldstone.ai/jobs/revenue-operations",
        75,
      ),
    ],
  },
  {
    ...shared,
    id: "0de82464-b357-46cf-a24e-7f4946774e7f",
    companyName: "Mosaic Freight",
    companyDomain: "mosaicfreight.com",
    companySize: "201–500",
    industry: "Logistics software",
    geography: "Copenhagen, DK",
    personName: "Nina Sørensen",
    jobTitle: "Commercial Director",
    email: null,
    emailVerified: false,
    phone: "+45 33 14 88 20",
    phoneVerified: true,
    linkedinUrl: "https://www.linkedin.com/in/nina-sorensen-commercial",
    confidence: 68,
    confidenceBand: "medium",
    status: "needs_review",
    doNotContact: false,
    buyingSignals: ["Entered two new markets"],
    evidence: [
      evidence(
        "d5f1082d-84a0-436b-b34d-ddc61fb6f9be",
        "company",
        "Mosaic Freight market update",
        "Mosaic Freight announced expansion into Belgium and the Netherlands.",
        "https://mosaicfreight.com/news/benelux",
        71,
      ),
    ],
  },
  {
    ...shared,
    id: "131d6b73-6c77-4da6-91af-acde667327d7",
    companyName: "Foundry Health",
    companyDomain: "foundryhealth.co",
    companySize: "51–200",
    industry: "Health technology",
    geography: "Dublin, IE",
    personName: "Ava Byrne",
    jobTitle: "VP Commercial",
    email: "ava@foundryhealth.co",
    emailVerified: true,
    phone: null,
    phoneVerified: false,
    linkedinUrl: "https://www.linkedin.com/in/ava-byrne",
    confidence: 53,
    confidenceBand: "low",
    status: "new",
    doNotContact: false,
    buyingSignals: ["Commercial leadership change"],
    evidence: [
      evidence(
        "85f7310d-c0aa-42c3-8cd6-fe49d9fd1059",
        "person",
        "Foundry Health leadership",
        "Ava joined recently; ownership of outbound acquisition is not yet confirmed.",
        "https://foundryhealth.co/about",
        55,
      ),
    ],
  },
  {
    ...shared,
    id: "66325f8b-acde-4f29-a7ad-53aa7c1c840a",
    companyName: "Harbor Stack",
    companyDomain: "harborstack.dev",
    companySize: "11–50",
    industry: "Developer tools",
    geography: "Lisbon, PT",
    personName: "Miguel Costa",
    jobTitle: "Head of Sales",
    email: "miguel@harborstack.dev",
    emailVerified: true,
    phone: "+351 21 555 0198",
    phoneVerified: true,
    linkedinUrl: "https://www.linkedin.com/in/miguel-costa-sales",
    confidence: 91,
    confidenceBand: "high",
    status: "suppressed",
    doNotContact: true,
    buyingSignals: ["Outbound team expansion"],
    evidence: [
      evidence(
        "0f0c0554-690a-446f-902c-cce203d71712",
        "intent",
        "Harbor Stack sales hiring",
        "The company is expanding sales, but this record is suppressed by workspace policy.",
        "https://harborstack.dev/careers",
        93,
      ),
    ],
  },
];

export const demoIcpProfile: IcpProfile = {
  id: DEMO_ICP_ID,
  organizationId: "demo-organization",
  campaignId: DEMO_CAMPAIGN_ID,
  name: "European B2B SaaS revenue teams",
  summary:
    "Growth-stage software companies building a repeatable outbound motion after early traction, where a senior revenue owner is accountable for pipeline quality.",
  confidence: 91,
  evidenceCount: 18,
  companyProfile: {
    industries: ["B2B SaaS", "Fintech", "Developer tools", "Analytics"],
    employeeRange: "25–500 employees",
    revenueRange: "$2M–$80M annual revenue",
    maturity: "Seed through Series B, or bootstrapped with proven demand",
    geographies: ["United Kingdom", "DACH", "Benelux", "Nordics"],
  },
  buyerRoles: [
    {
      title: "VP Revenue / CRO",
      priority: "primary",
      motivation: "Needs repeatable, evidence-backed pipeline without scaling a research team.",
    },
    {
      title: "Head of Growth / Demand Generation",
      priority: "secondary",
      motivation: "Owns qualified pipeline and channel experimentation.",
    },
    {
      title: "Revenue Operations",
      priority: "influencer",
      motivation: "Protects data quality, workflow control and reporting integrity.",
    },
  ],
  painPoints: [
    "Prospecting lists decay before campaigns launch.",
    "Researchers cannot show why a lead belongs in the campaign.",
    "Generic automation damages sender reputation and buyer trust.",
  ],
  buyingSignals: [
    "Hiring SDR, growth or Revenue Operations roles",
    "Recent funding, market expansion or a new commercial leader",
    "Public shift from founder-led sales to a repeatable motion",
  ],
  exclusions: [
    "Consumer-only companies",
    "Organizations without a visible commercial owner",
    "Suppressed contacts or companies with unresolved compliance restrictions",
  ],
  evidence: [
    evidence(
      "965708c8-b88f-41f8-ae08-dbc3dc7abb28",
      "intent",
      "European SaaS hiring sample",
      "Across the qualified sample, revenue hiring and geographic expansion repeatedly precede outbound investment.",
      "https://example.com/research/european-saas-hiring",
      93,
    ),
    evidence(
      "c56bb835-d238-434d-af0c-a5f5bd0e81be",
      "company",
      "Campaign market synthesis",
      "The strongest-fit companies share a clear commercial owner and evidence of moving beyond referral-led growth.",
      "https://example.com/research/market-synthesis",
      89,
    ),
  ],
  createdAt,
  updatedAt,
};
