import * as React from "react";
import { Slot } from "radix-ui";
import { ChevronRight, MoreHorizontal } from "lucide-react";
import { cn } from "@/lib/utils";
const Breadcrumb = (props: React.ComponentProps<"nav">) => <nav aria-label="breadcrumb" {...props} />;
const BreadcrumbList = ({ className, ...props }: React.ComponentProps<"ol">) => <ol className={cn("flex flex-wrap items-center gap-1.5 text-sm text-muted-foreground", className)} {...props} />;
const BreadcrumbItem = ({ className, ...props }: React.ComponentProps<"li">) => <li className={cn("inline-flex items-center gap-1.5", className)} {...props} />;
const BreadcrumbLink = ({ asChild, className, ...props }: React.ComponentProps<"a"> & { asChild?: boolean }) => { const Component = asChild ? Slot.Slot : "a"; return <Component className={cn("transition-colors hover:text-foreground", className)} {...props} />; };
const BreadcrumbPage = ({ className, ...props }: React.ComponentProps<"span">) => <span role="link" aria-disabled="true" aria-current="page" className={cn("font-medium text-foreground", className)} {...props} />;
const BreadcrumbSeparator = ({ children, className, ...props }: React.ComponentProps<"li">) => <li role="presentation" aria-hidden="true" className={cn("[&>svg]:size-3.5", className)} {...props}>{children ?? <ChevronRight />}</li>;
const BreadcrumbEllipsis = ({ className, ...props }: React.ComponentProps<"span">) => <span role="presentation" aria-hidden="true" className={cn("grid size-9 place-items-center", className)} {...props}><MoreHorizontal className="size-4" /><span className="sr-only">More</span></span>;
export { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage, BreadcrumbSeparator, BreadcrumbEllipsis };
